language: java
jdk:
- oraclejdk8
addons:
  sonarqube:
    organization: nebrass-github
    token:
      secure: PQo31evv5ts7f156iBwCZf6Kj2ipU8TOk0wCRDVgxOdD43wKMrEja+g85O+PEDQzoI0VlMRYpCOjuFlQtvl8MmZgUOXQ+HeWbycJErIyufRkVY6OaI/TroG+0Inn1+5uYPMJqdlUd8usuJNBZxMu6mugBUI5lskoKqM9d+3srj3OeBAVA80ruaPFh7/LjkkDA51vDgQ6PvyQ6PlKCZagLD45mEo3pp6cXFJzPjYpUIcUbQDCJsZ8cyU3tdc7VddmGbR/Yk9gZkTGojBlLVu8xGVhcW6SoZ7nfhxHczmeTpH3jSfMPdaJ7MRuSwVLwLqr/wnNrE5KfmbeIPUem2GbmGazfXtipA4hW3Bvw0qLTJsVrt73YFkfZeA+LH5lo32CD1elaefaJLDlfRV+ieqtCDpAbLGVKWi1BD2bSbScVr78yrDVt4oDOZGXFTHEhPRzz1/PAfiPLfaSFs7mGvlfQGK6qJxGiOms7DNq7LIxDOTmp6FbewlVLIsw2uAdW5oM3fFbEowOXRxEWpvn0/ib7q1OLLw9u7gJrBpDs2+un4t9WM4Kd96AsgDM1H65uPntGJ4hvS58dYo6grJ4jw+JQHb9esnIMCrzM6k1Z5Zp33tGX17wFvDoKcqgp6rVT/zPzkYqTxd9VLBnb3xAQvmxo1hR4pIexu/zYDkJsLxkDUY=
    branches:
      - master
      - dev
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
env:
  global:
    secure: im7cPbtq8D1EjDXXnb6lhovv9kj+mwAwu1LsEI8++Dit25mihFv99fuJI1VoskCuPqDxhKMWo604sDk2M4178+GXhFSNk0mt7NH8j1KD/x2JlX2+0R8qK1beo5tbuDPx+Qi6dKYP8TYgIlBCAeEPDcM65Jk+EadEiOfvAWYyDDzDgunS+Nutep5JFOTBrNyBUKp9SVQQtAO4Rwwfn+MURA57KzgEdESHjVcsAxTZ5gAWoGm/2hwYSx8vxcDwhb+dtrExB7PZJozenXg82LlcYD3vLnBsoL+8WtDOLiwkXRc6YiLxx65eGMUmp7jDXByW4nfrVVG2zQC80obRnEY8/UXQ7s4RI6DbW8maa7Sr1X52arbpxwdFmCOmvb2ipcFhKnOVWZgTgMfxYWbntfMqcWhLpiY1be2F7zrUpfhdS15VdJgTDbmT9OCb35PNdeuXv18Ot23pNYD9tXQOvKn/7ulfo1sCI6Zkc19ntYR0FEYZY5mRPoEmkhI8dKbEafmwWeYDXUWDYVMFqTWcbk4GEF5N+uPeShuObBDGa94AQSeQA2BGb/hebSfJh9MwFXF7fAfbU8RiWg7beIOsZanO32Ccbac8mxQINBw8Gjbqin/7TgLZEP3lcmQhOWuNH64SX/AjjwD+YOgmo9gseNX7U6T8pZR9r/ALDK7fExCFxp0=
